services:
  job-analytics-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-analytics-dashboard
    environment:
      NODE_ENV: production
      PORT: "4000"
      HOSTNAME: 0.0.0.0
    env_file:
      - .env.local
    ports:
      - "4000:4000"
    restart: unless-stopped
